services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
    - CHROMA_DB_DIR=chroma_db
    labels:
    - traefik.enable=true
    - traefik.http.routers.mutant-backend.rule=Host(`dev-api.mutante.grupocin.com.br`)
    - traefik.http.services.mutant-backend.loadbalancer.server.port=8000
    ports:
    - '8000'
    restart: unless-stopped
    volumes:
    - mutant-chromadb:/app/chroma_db
    - ./docs:/docs:ro
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
    - backend
    environment:
    - NEXT_PUBLIC_API_PORT=${BACKEND_PORT:-8010}
    labels:
    - traefik.enable=true
    - traefik.http.routers.mutant-frontend.rule=Host(`dev-mutante.grupocin.com.br`)
    - traefik.http.services.mutant-frontend.loadbalancer.server.port=3000
    ports:
    - '3000'
    restart: unless-stopped
volumes:
  mutant-chromadb: null
